// SHOPPPPPP
export const READ_PRODUCTS = 'READ_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ONE_FROM_CART = 'DELETE_ONE_FROM_CART';
export const DELETE_ALL_FROM_CART = 'DELETE_ALL_FROM_CART';
export const BUY_CART = 'BUY_CART';
export const FILTER = 'FILTER';
export const NEXT_PAGINATION = 'NEXT_PAGINATION';
export const PREV_PAGINATION = 'PREV_PAGINATION';
export const SORT_PRICE = 'SORT_PRICE';
export const SORT_ALPHA = 'SORT_ALPHA';
