// SHOPPPPPP
export const READ_PRODUCTS = 'READ_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ONE_FROM_CART = 'DELETE_ONE_FROM_CART';
export const DELETE_ALL_FROM_CART = 'DELETE_ALL_FROM_CART';
export const BUY_CART = 'BUY_CART';
